import React, { useEffect, useMemo, useState } from 'react';
import { Alert, KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { ScaledText as Text } from '../components/ScaledText';
import { Holding } from '../data/portfolio';
import { estimateMonthsToGoal, money, portfolioMetrics } from '../domain/metrics';
import { TwseQuote } from '../services/twse';
import { Card, Header, palette, Progress, SectionTitle } from '../components/Ui';
import DatePickerField from '../components/DatePickerField';
import { GoalSettings, LayoutSettings } from '../storage/appStorage';
import { PageLayoutEditor } from '../components/PageLayoutEditor';

const GOAL_CHOICES=[{key:'passiveIncome',label:'每月被動收入目標',category:'目標'},{key:'currentCashflow',label:'目前月均現金流',category:'現況'},{key:'totalAssetsTarget',label:'總資產目標',category:'目標'},{key:'currentAssets',label:'目前資產',category:'現況'},{key:'assetGap',label:'距離目標差額',category:'進度'},{key:'progress',label:'資產目標進度',category:'進度'},{key:'eta',label:'預計達成時間',category:'進度'},{key:'monthlyContribution',label:'每月投入目標',category:'目標'},{key:'targetDate',label:'目標日期',category:'日期'},{key:'cashYield',label:'假設現金殖利率',category:'假設'},{key:'annualReturn',label:'假設年化報酬率',category:'假設'},{key:'milestones',label:'25/50/75/100% 里程碑',category:'進度'}];
type Draft={monthlyPassiveIncomeTarget:string;monthlyContributionTarget:string;totalAssetsTarget:string;targetDate:string;assumedCashYield:string;assumedAnnualReturn:string};
const toDraft=(g:GoalSettings):Draft=>({monthlyPassiveIncomeTarget:String(g.monthlyPassiveIncomeTarget),monthlyContributionTarget:String(g.monthlyContributionTarget),totalAssetsTarget:String(g.totalAssetsTarget),targetDate:g.targetDate,assumedCashYield:String(Number((g.assumedCashYield*100).toFixed(2))),assumedAnnualReturn:String(Number((g.assumedAnnualReturn*100).toFixed(2)))});
const num=(v:string)=>Number(v.replace(/,/g,'').trim());

export default function GoalScreen({holdings,quotes,goals,onChange,layout,onLayoutChange}:{holdings:Holding[];quotes:Record<string,TwseQuote>;goals:GoalSettings;onChange:(g:GoalSettings)=>void;layout:LayoutSettings;onLayoutChange:(p:Partial<LayoutSettings>)=>void}){
 const [layoutOpen,setLayoutOpen]=useState(false); const [editorOpen,setEditorOpen]=useState(false); const page=layout.pageLayouts.goal??{fields:GOAL_CHOICES.map(x=>x.key),spans:{passiveIncome:3,currentCashflow:3,totalAssetsTarget:3,currentAssets:3,assetGap:3,progress:3,eta:3,monthlyContribution:3,targetDate:3,cashYield:3,annualReturn:3,milestones:6}}; const selected=page.fields;
 const p=portfolioMetrics(holdings,quotes); const targetAssets=goals.totalAssetsTarget>0?goals.totalAssetsTarget:(goals.assumedCashYield>0?goals.monthlyPassiveIncomeTarget*12/goals.assumedCashYield:0); const gap=Math.max(0,targetAssets-p.marketValue); const progress=Math.min(100,targetAssets>0?p.marketValue/targetAssets*100:0); const months=estimateMonthsToGoal(p.marketValue,targetAssets,goals.monthlyContributionTarget,goals.assumedAnnualReturn); const years=Math.floor(months/12),rem=months%12;
 const values:any={passiveIncome:['每月被動收入目標',`${money(goals.monthlyPassiveIncomeTarget)} / 月`],currentCashflow:['目前月均現金流',`${money(p.monthlyCashflow)} / 月`],totalAssetsTarget:['總資產目標',money(targetAssets)],currentAssets:['目前資產',money(p.marketValue)],assetGap:['距離目標差額',money(gap)],progress:['資產目標進度',`${progress.toFixed(2)}%`],eta:['預計達成時間',`約 ${years} 年 ${rem} 個月`],monthlyContribution:['每月投入目標',money(goals.monthlyContributionTarget)],targetDate:['目標日期',goals.targetDate],cashYield:['假設現金殖利率',`${(goals.assumedCashYield*100).toFixed(2)}%`],annualReturn:['假設年化報酬率',`${(goals.assumedAnnualReturn*100).toFixed(2)}%`]};
 const editableKeys=new Set(['passiveIncome','totalAssetsTarget','monthlyContribution','targetDate','cashYield','annualReturn']);
 return <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Header title="目標中心" subtitle="目標數值可直接修改、儲存與追蹤" slogan="先把目標設清楚，再讓數字替你工作。" onLayoutPress={()=>setLayoutOpen(true)}/><PageLayoutEditor visible={layoutOpen} title="目標頁排版設定" choices={GOAL_CHOICES} selected={selected} spans={page.spans} onClose={()=>setLayoutOpen(false)} onSave={(fields,spans)=>onLayoutChange({pageLayouts:{...layout.pageLayouts,goal:{fields,spans}}})}/>
 <Card><View style={styles.head}><SectionTitle icon="◎" title="目標儀表板" subtitle="可修改的目標卡片可直接點擊"/><Pressable onPress={()=>setEditorOpen(true)} style={styles.edit}><Text style={styles.editText}>✎ 編輯目標</Text></Pressable></View><View style={styles.metricGrid}>{selected.filter(k=>k!=='milestones').map(k=>{const a=values[k]??[k,'—'];const editable=editableKeys.has(k);return <Pressable key={k} disabled={!editable} onPress={()=>setEditorOpen(true)} style={[styles.metricBox,{width:(page.spans[k]||6)===6?'100%':(page.spans[k]||6)===3?'49%':'32%'},editable&&styles.metricEditable]}><Text style={styles.muted}>{a[0]}{editable?'  ✎':''}</Text><Text style={styles.metricValue}>{a[1]}</Text></Pressable>})}</View>{selected.includes('progress')?<Progress value={progress}/>:null}</Card>
 {selected.includes('milestones')?<Card><SectionTitle title="里程碑"/><ScrollView horizontal showsHorizontalScrollIndicator><View style={styles.milestoneLine}>{[25,50,75,100].map(v=><View key={v} style={styles.mile}><View style={[styles.dot,progress>=v&&styles.dotDone]}><Text style={styles.dotText}>{progress>=v?'✓':''}</Text></View><Text style={styles.milePct}>{v===100?'達標':`${v}%`}</Text><Text style={styles.mileAmount}>{money(targetAssets*v/100)}</Text></View>)}</View></ScrollView></Card>:null}
 <GoalEditModal visible={editorOpen} goals={goals} onClose={()=>setEditorOpen(false)} onSave={g=>{onChange(g);setEditorOpen(false);Alert.alert('目標已儲存','新的目標數值已立即套用並保存。')}}/>
 </ScrollView>;
}

function GoalEditModal({visible,goals,onClose,onSave}:{visible:boolean;goals:GoalSettings;onClose:()=>void;onSave:(g:GoalSettings)=>void}){
 const insets=useSafeAreaInsets(); const [draft,setDraft]=useState<Draft>(()=>toDraft(goals)); useEffect(()=>{if(visible)setDraft(toDraft(goals))},[visible,goals]);
 const save=()=>{const passive=num(draft.monthlyPassiveIncomeTarget),monthly=num(draft.monthlyContributionTarget),assets=num(draft.totalAssetsTarget),cash=num(draft.assumedCashYield),annual=num(draft.assumedAnnualReturn);if(![passive,monthly,assets,cash,annual].every(Number.isFinite)||passive<0||monthly<0||assets<=0||cash<0||annual<0)return Alert.alert('目標設定','請確認所有金額與百分比。');onSave({...goals,monthlyPassiveIncomeTarget:passive,monthlyContributionTarget:monthly,totalAssetsTarget:assets,targetDate:draft.targetDate,assumedCashYield:cash/100,assumedAnnualReturn:annual/100});};
 return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><SafeAreaView style={styles.modalSafe} edges={['top','left','right']}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':'height'}><View style={styles.modalHead}><View><Text style={styles.modalTitle}>編輯財務目標</Text><Text style={styles.modalSub}>輸入內容不會在輸入途中被格式化或重置。</Text></View><Pressable onPress={onClose} style={styles.close}><Text>✕</Text></Pressable></View><ScrollView contentContainerStyle={[styles.form,{paddingBottom:100+insets.bottom}]} keyboardShouldPersistTaps="handled"><Field label="每月被動收入目標" value={draft.monthlyPassiveIncomeTarget} onChange={v=>setDraft(d=>({...d,monthlyPassiveIncomeTarget:v}))}/><Field label="每月投入目標" value={draft.monthlyContributionTarget} onChange={v=>setDraft(d=>({...d,monthlyContributionTarget:v}))}/><Field label="總資產目標" value={draft.totalAssetsTarget} onChange={v=>setDraft(d=>({...d,totalAssetsTarget:v}))}/><Field label="假設現金殖利率 %" value={draft.assumedCashYield} onChange={v=>setDraft(d=>({...d,assumedCashYield:v}))}/><Field label="假設年化報酬率 %" value={draft.assumedAnnualReturn} onChange={v=>setDraft(d=>({...d,assumedAnnualReturn:v}))}/><DatePickerField label="目標日期" value={draft.targetDate} onChange={v=>setDraft(d=>({...d,targetDate:v}))}/></ScrollView><View style={[styles.actionBar,{paddingBottom:12+insets.bottom}]}><Pressable onPress={onClose} style={styles.cancel}><Text style={styles.cancelText}>取消</Text></Pressable><Pressable onPress={save} style={styles.save}><Text style={styles.saveText}>儲存目標</Text></Pressable></View></KeyboardAvoidingView></SafeAreaView></Modal>;
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><TextInput value={value} onChangeText={onChange} keyboardType="decimal-pad" returnKeyType="done" style={styles.input}/></View>}
const styles=StyleSheet.create({content:{paddingBottom:110},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:8},edit:{minHeight:40,paddingHorizontal:12,borderRadius:10,backgroundColor:palette.greenSoft,justifyContent:'center'},editText:{color:palette.green,fontSize:10,fontWeight:'900'},metricGrid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',gap:8},metricBox:{borderWidth:1,borderColor:palette.line,borderRadius:10,padding:10,minHeight:70,backgroundColor:palette.surfaceSoft},metricEditable:{borderColor:'#A8E6CF'},muted:{color:palette.muted,fontSize:10,flexWrap:'wrap'},metricValue:{color:palette.text,fontWeight:'900',fontSize:14,textAlign:'right',marginTop:6,flexWrap:'wrap'},milestoneLine:{flexDirection:'row',minWidth:600,justifyContent:'space-between'},mile:{width:140,alignItems:'center'},dot:{width:32,height:32,borderRadius:16,borderWidth:4,borderColor:palette.track,alignItems:'center',justifyContent:'center'},dotDone:{backgroundColor:palette.green,borderColor:palette.green},dotText:{fontWeight:'900',color:'#fff'},milePct:{color:palette.text,fontWeight:'900',marginTop:7,fontSize:12},mileAmount:{color:palette.muted,fontSize:9,marginTop:3,textAlign:'center'},modalSafe:{flex:1,backgroundColor:'#F7FAFC'},modalHead:{padding:16,backgroundColor:'#fff',borderBottomWidth:1,borderBottomColor:palette.line,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},modalTitle:{fontSize:22,fontWeight:'900',color:palette.text},modalSub:{fontSize:10,color:palette.muted,marginTop:4},close:{width:40,height:40,borderRadius:10,backgroundColor:palette.surfaceSoft,alignItems:'center',justifyContent:'center'},form:{padding:16,gap:10},field:{minWidth:0},fieldLabel:{fontSize:10,color:palette.muted,fontWeight:'800',marginBottom:5},input:{minHeight:50,borderWidth:1,borderColor:palette.line,borderRadius:10,paddingHorizontal:12,fontSize:18,color:palette.text,backgroundColor:'#fff'},actionBar:{position:'absolute',left:0,right:0,bottom:0,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:palette.line,paddingHorizontal:12,paddingTop:12,flexDirection:'row',gap:10},cancel:{flex:1,minHeight:50,borderRadius:10,backgroundColor:palette.surfaceSoft,alignItems:'center',justifyContent:'center'},cancelText:{fontWeight:'900',color:palette.text},save:{flex:2,minHeight:50,borderRadius:10,backgroundColor:palette.green,alignItems:'center',justifyContent:'center'},saveText:{color:'#fff',fontWeight:'900'}});
