import React, { useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { ScaledText as Text } from '../components/ScaledText';
import { Holding } from '../data/portfolio';
import { contributionPlan, money, portfolioMetrics, quote, signedMoney, signedPercent } from '../domain/metrics';
import { TwseQuote } from '../services/twse';
import { Card, EtfCodeBadge, Header, palette, Progress, RefreshText, SectionTitle } from '../components/Ui';
import { DashboardField, GoalSettings, LayoutSettings } from '../storage/appStorage';
import { LayoutChoice, PageLayoutEditor } from '../components/PageLayoutEditor';

type Props={holdings:Holding[];quotes:Record<string,TwseQuote>;lastSuccessAt?:number;quoteError?:string;refresh:()=>void;goals:GoalSettings;layout:LayoutSettings;onLayoutChange:(p:Partial<LayoutSettings>)=>void;onOpenGoal:()=>void;onOpenDaily:()=>void};
const BASE_HOME_CHOICES:LayoutChoice[]=[
 {key:'marketValue',label:'總資產',category:'資產'},{key:'cost',label:'持有總成本',category:'資產'},{key:'costPnl',label:'成本損益',category:'損益'},{key:'costPnlPct',label:'成本損益 %',category:'損益'},{key:'totalPnl',label:'含息總損益',category:'損益'},{key:'totalPnlPct',label:'含息總損益 %',category:'損益'},{key:'todayPnl',label:'今日損益',category:'損益'},{key:'todayPnlPct',label:'今日損益 %',category:'損益'},
 {key:'cumulativeDividend',label:'累積配息',category:'配息'},{key:'monthDividend',label:'本月配息',category:'配息'},{key:'annualDividend',label:'預估年配息',category:'配息'},{key:'monthlyCashflow',label:'月均現金流',category:'配息'},{key:'cashYield',label:'預估現金殖利率',category:'配息'},
 {key:'monthContribution',label:'本月投入',category:'投入'},{key:'monthGoal',label:'本月投入目標',category:'投入'},{key:'monthGoalProgress',label:'本月目標進度',category:'投入'},{key:'totalAssetsGoal',label:'總資產目標',category:'目標'},{key:'passiveIncomeGoal',label:'月被動收入目標',category:'目標'},{key:'goalTargetDate',label:'目標日期',category:'目標'},
 {key:'health',label:'健康分數',category:'分析'},{key:'holdingCount',label:'ETF 檔數',category:'分析'},{key:'nextAllocation',label:'下一筆配置',category:'分析'},{key:'marketState',label:'市場狀態',category:'市場'},{key:'updatedAt',label:'最後更新時間',category:'市場'},
 {key:'nextDividend',label:'最近配息提醒',category:'日期提醒'},{key:'lastBuyReminder',label:'最後買進日提醒',category:'日期提醒'}
];
const ETF_METRICS=[['shares','持有股數','資產'],['price','現價','市場'],['marketValue','市值','資產'],['totalCost','總成本','資產'],['avgCost','平均成本','資產'],['costPnl','成本損益','損益'],['costPnlPct','成本損益 %','損益'],['todayPnl','今日損益','損益'],['todayPnlPct','今日損益 %','損益'],['cumulativeDividend','累積配息','配息'],['annualDividend','預估年配息','配息'],['cashYield','殖利率','配息'],['lastBuyDate','最後買進日','日期提醒'],['purchaseCount','買進筆數','其他'],['buyFee','手續費總計','其他']] as const;
function etfChoices(holdings:Holding[]):LayoutChoice[]{return holdings.flatMap(h=>ETF_METRICS.map(([metric,label,cat])=>({key:`etf:${h.symbol}:${metric}`,label:`${h.symbol} ${label}`,category:`ETF 個別資料`,hint:h.name})))}

export default function HomeScreen({holdings,quotes,lastSuccessAt,quoteError,refresh,goals,layout,onLayoutChange,onOpenGoal,onOpenDaily}:Props){
 const [layoutOpen,setLayoutOpen]=useState(false); const choices=useMemo(()=>BASE_HOME_CHOICES,[]);
 const m=portfolioMetrics(holdings,quotes); const plan=contributionPlan(holdings,quotes,goals.monthlyContributionTarget||10000); const now=new Date(); const ym=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`; const monthRecords=holdings.flatMap(h=>(h.purchaseRecords??[]).map(r=>({h,r}))).filter(x=>x.r.date.startsWith(ym)); const monthContribution=monthRecords.reduce((s,x)=>s+x.r.totalCost,0); const progress=goals.monthlyContributionTarget>0?Math.min(100,monthContribution/goals.monthlyContributionTarget*100):0;
 const cumulativeDividend=holdings.reduce((s,h)=>s+Number((h as any).receivedDividend??0),0); const totalPnl=m.pnl+cumulativeDividend; const totalPnlPct=m.cost>0?totalPnl/m.cost:0; const todayPnl=holdings.reduce((s,h)=>{const q:any=quotes[h.symbol];const prev=Number(q?.previousClose??q?.open??q?.price??h.fallbackPrice??h.avgCost);const price=Number(q?.price??h.fallbackPrice??h.avgCost);return s+(price-prev)*h.shares},0); const todayPnlPct=m.marketValue-todayPnl>0?todayPnl/(m.marketValue-todayPnl):0;
 const explainHealth=()=>Alert.alert('資產健康分數如何計算',`目前 ${m.health}/100\n\n基礎 100 分，再依分散度、集中度、成本損益與殖利率風險調整。`);
 const explainPlan=()=>Alert.alert('下一筆資金配置',`目前依「目標比重缺口」分配下一筆 ${money(goals.monthlyContributionTarget||10000)}。`);
 const fieldValue=(f:string):[string,string,string,number|undefined]=>{
  if(f.startsWith('etf:')){const [,symbol,metric]=f.split(':');const h=holdings.find(x=>x.symbol===symbol);if(!h)return[f,'—','',undefined];const q:any=quotes[symbol];const price=Number(q?.price??h.fallbackPrice??h.avgCost);const value=price*h.shares;const pureCost=h.purchaseRecords?.length?h.purchaseRecords.reduce((sum,r)=>sum+Number(r.purchaseCost||0),0):h.shares*(h.tradeAvgPrice??h.avgCost);const fee=Number(h.buyFee??h.purchaseRecords?.reduce((sum,r)=>sum+Number(r.fee||0),0)??0);const cost=pureCost;const totalCost=pureCost+fee;const pnl=value-pureCost;const prev=Number(q?.previousClose??q?.open??price);const tp=(price-prev)*h.shares;const lastBuy=(h.purchaseRecords??[]).map(r=>r.date).sort().at(-1)||'—';const map:any={shares:[`${symbol} 持有股數`,`${h.shares.toLocaleString('zh-TW')} 股`,h.name],price:[`${symbol} 現價`,quote(price),h.name],marketValue:[`${symbol} 市值`,money(value),h.name],pureCost:[`${symbol} 純買進成本`,money(pureCost),h.name],totalCost:[`${symbol} 總成本`,money(totalCost),h.name],avgCost:[`${symbol} 平均成本`,quote(h.tradeAvgPrice??h.avgCost),h.name],costPnl:[`${symbol} 成本損益`,signedMoney(pnl),h.name,pnl],costPnlPct:[`${symbol} 成本損益 %`,signedPercent(cost>0?pnl/cost:0),h.name,pnl],todayPnl:[`${symbol} 今日損益`,signedMoney(tp),h.name,tp],todayPnlPct:[`${symbol} 今日損益 %`,signedPercent(prev>0?(price-prev)/prev:0),h.name,tp],cumulativeDividend:[`${symbol} 累積配息`,money(Number((h as any).receivedDividend??0)),h.name],annualDividend:[`${symbol} 預估年配息`,money(h.shares*h.annualDividendPerShare),h.name],cashYield:[`${symbol} 殖利率`,signedPercent(value>0?h.shares*h.annualDividendPerShare/value:0),h.name],lastBuyDate:[`${symbol} 最後買進日`,lastBuy,h.name],purchaseCount:[`${symbol} 買進筆數`,`${h.purchaseRecords?.length??1} 筆`,h.name],buyFee:[`${symbol} 手續費總計`,money(h.buyFee??0,0),h.name]};return map[metric]??[`${symbol} ${metric}`,'—',h.name]}
  const map:any={marketValue:['總資產',money(m.marketValue),'目前持股市值'],cost:['持有總成本',money(m.totalCost),'純買進成本 + 手續費'],costPnl:['成本損益',signedMoney(m.pnl),signedPercent(m.pnlPct),m.pnl],costPnlPct:['成本損益 %',signedPercent(m.pnlPct),'',m.pnl],totalPnl:['含息總損益',signedMoney(totalPnl),`含累積配息 ${money(cumulativeDividend)}`,totalPnl],totalPnlPct:['含息總損益 %',signedPercent(totalPnlPct),'',totalPnl],todayPnl:['今日損益',signedMoney(todayPnl),'依 TWSE 與昨收估算',todayPnl],todayPnlPct:['今日損益 %',signedPercent(todayPnlPct),'',todayPnl],cumulativeDividend:['累積配息',money(cumulativeDividend),'已領配息'],monthDividend:['本月配息',money(0),'依股息事件 / 已領紀錄'],annualDividend:['預估年配息',money(m.annualDividend),'依目前持股估算'],monthlyCashflow:['月均現金流',money(m.monthlyCashflow),'依配息估值'],cashYield:['預估現金殖利率',signedPercent(m.cashYield),''],monthContribution:['本月投入',money(monthContribution),'由購入紀錄彙整'],monthGoal:['本月投入目標',money(goals.monthlyContributionTarget),''],monthGoalProgress:['本月目標進度',`${progress.toFixed(0)}%`,`${money(monthContribution)} / ${money(goals.monthlyContributionTarget)}`],totalAssetsGoal:['總資產目標',money(goals.totalAssetsTarget),''],passiveIncomeGoal:['月被動收入目標',money(goals.monthlyPassiveIncomeTarget),''],goalTargetDate:['目標日期',goals.targetDate||'—',''],health:['健康分數',`${m.health}/100`,''],holdingCount:['ETF 檔數',`${holdings.length} 檔`,''],nextAllocation:['下一筆配置',plan[0]?`${plan[0].symbol} ${money(plan[0].amount)}`:'尚無配置','依目標比重缺口'],marketState:['市場狀態',Object.keys(quotes).length?'TWSE 已連線':'等待行情',''],updatedAt:['最後更新時間',lastSuccessAt?new Date(lastSuccessAt).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'}):'—',''],nextDividend:['最近配息提醒','查看股息頁',''],lastBuyReminder:['最後買進日提醒','查看持倉紀錄','']};return map[f]??[f,'—','']
 };
 return <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Header title={layout.appTitle||'ETF財務管家'} subtitle={layout.appSubtitle||'所有關鍵數值都可追溯來源'} slogan="投資，是更好的自己走向未來。" onLayoutPress={()=>setLayoutOpen(true)}/><PageLayoutEditor visible={layoutOpen} title="首頁排版設定" choices={choices} selected={layout.homeFields} spans={layout.homeFieldSpans} onClose={()=>setLayoutOpen(false)} onSave={(keys,spans)=>onLayoutChange({homeFields:keys as DashboardField[],homeFieldSpans:spans})}/>
 <Pressable onPress={onOpenDaily}><Card><View style={styles.rowBetween}><Text style={styles.cardLabel}>首頁自訂資訊</Text><RefreshText lastSuccessAt={lastSuccessAt} error={quoteError} onPress={refresh}/></View><View style={[styles.dynamicGrid,{gap:layout.compactCards?5:8}]}>{layout.homeFields.map(f=>{const a=fieldValue(f);const sign=a[3];return <View key={f} style={[styles.dynamicCell,{width:(layout.homeFieldSpans[f]||6)===6?'100%':(layout.homeFieldSpans[f]||6)===3?'49%':'32%',padding:layout.compactCards?8:12}]}><Text style={[styles.dynamicLabel,{fontSize:10}]}>{a[0]}</Text><Text style={[styles.dynamicValue,{fontSize:16},typeof sign==='number'&&{color:sign>=0?palette.red:palette.green}]}>{a[1]}</Text>{a[2]?<Text style={styles.dynamicSub}>{a[2]}</Text>:null}</View>})}</View>{layout.etfTemplateSelectedSymbols.length>0?<View style={styles.etfTemplateWrap}><Text style={styles.etfTemplateTitle}>單股 ETF 顯示模板</Text>{layout.etfTemplateSelectedSymbols.map(symbol=>{const h=holdings.find(x=>x.symbol===symbol);if(!h)return null;return <View key={symbol} style={styles.etfBlock}><View style={styles.etfHeadRow}><EtfCodeBadge symbol={symbol}/><Text style={styles.etfHead}>{h.name}</Text></View><View style={styles.dynamicGrid}>{layout.etfTemplateFields.map(metric=>{const a=fieldValue(`etf:${symbol}:${metric}`);const sign=a[3];const span=layout.etfTemplateFieldSpans[metric]||3;return <View key={`${symbol}-${metric}`} style={[styles.dynamicCell,{width:span===6?'100%':span===3?'49%':'32%',padding:layout.compactCards?8:12}]}><Text style={[styles.dynamicLabel,{fontSize:10}]}>{a[0].replace(`${symbol} `,'')}</Text><Text style={[styles.dynamicValue,{fontSize:16},typeof sign==='number'&&{color:sign>=0?palette.red:palette.green}]}>{a[1]}</Text>{a[2]?<Text style={styles.dynamicSub}>{a[2]}</Text>:null}</View>})}</View></View>})}</View>:null}<Text style={styles.tapHint}>點擊查看每日損益走勢 ›</Text></Card></Pressable>
 <View style={styles.twoCol}><Pressable style={styles.flexPress} onPress={explainHealth}><Card style={styles.flexCard}><SectionTitle title="資產健康分數"/><View style={styles.scoreCircle}><Text style={styles.score}>{m.health}</Text><Text style={styles.scoreSub}>/100</Text></View><Text style={styles.goodText}>點擊查看計算依據</Text></Card></Pressable><Pressable style={styles.flexPress} onPress={explainPlan}><Card style={styles.flexCard}><SectionTitle title="下一筆資金配置"/>{plan.slice(0,3).map((item,i)=><View key={item.symbol} style={{marginTop:10}}><View style={styles.rowBetween}><Text style={styles.symbol}>{item.symbol}</Text><Text style={styles.planAmount}>{money(item.amount)}</Text></View><Progress value={item.targetWeight*100} tone={i===1?'green':'blue'}/></View>)}</Card></Pressable></View>
 <Pressable onPress={onOpenGoal}><Card><SectionTitle icon="◎" title="本月目標進度"/><View style={styles.rowBetween}><Text style={styles.goalValue}>{money(monthContribution)} <Text style={styles.goalTarget}>/ {money(goals.monthlyContributionTarget)}</Text></Text><Text style={styles.progressPct}>{progress.toFixed(0)}%</Text></View><Progress value={progress}/></Card></Pressable>
 </ScrollView>;
}
const styles=StyleSheet.create({content:{paddingBottom:98},dynamicGrid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',marginTop:12},dynamicCell:{borderWidth:1,borderColor:palette.line,borderRadius:12,backgroundColor:palette.surfaceSoft,minHeight:72,justifyContent:'space-between'},dynamicLabel:{color:palette.muted,fontWeight:'800'},dynamicValue:{color:palette.text,fontWeight:'900',textAlign:'right'},dynamicSub:{color:palette.muted,fontSize:9,textAlign:'right'},rowBetween:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},cardLabel:{color:palette.text,fontWeight:'900',fontSize:18},twoCol:{flexDirection:'row',paddingHorizontal:16,gap:12},flexPress:{flex:1},flexCard:{marginHorizontal:0,minHeight:220},scoreCircle:{width:96,height:96,borderRadius:48,borderWidth:10,borderColor:palette.green,alignItems:'center',justifyContent:'center',alignSelf:'center'},score:{color:palette.text,fontSize:34,fontWeight:'900'},scoreSub:{color:palette.muted,fontSize:10},goodText:{color:palette.green,fontWeight:'900',textAlign:'center',marginTop:8,fontSize:10},symbol:{color:palette.text,fontWeight:'900',fontSize:12},planAmount:{color:palette.green,fontWeight:'900',fontSize:11},goalValue:{color:palette.green,fontWeight:'900',fontSize:23,marginTop:4},goalTarget:{color:palette.muted,fontSize:14},progressPct:{color:palette.green,fontSize:24,fontWeight:'900'},tapHint:{color:palette.blue,fontSize:9,fontWeight:'800',marginTop:10},etfTemplateWrap:{marginTop:16},etfTemplateTitle:{fontSize:14,fontWeight:'900',color:palette.text,marginBottom:8},etfBlock:{borderTopWidth:1,borderTopColor:palette.line,paddingTop:10,marginTop:8},etfHeadRow:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:6},etfHead:{fontSize:13,fontWeight:'900',color:palette.text,flex:1,flexWrap:'wrap'}});
