const fs=require('fs');
const patch=(file,fn)=>{const before=fs.readFileSync(file,'utf8');const after=fn(before);if(after===before)throw new Error(`No changes applied to ${file}`);fs.writeFileSync(file,after);console.log(`patched ${file}`)};
const replace=(src,needle,repl,label)=>{if(!src.includes(needle))throw new Error(`Missing patch anchor: ${label}`);return src.replace(needle,repl)};

patch('src/v3/screensBase.tsx',src=>{
 src=replace(src,
`function MonitorChoice({active,label,onPress}:{active:boolean;label:string;onPress:()=>void}){const p=theme();return <TouchableOpacity onPress={onPress} style={[s.choice,active&&s.choiceActive,active&&{borderColor:p?.accentColor??'#d4af37'}]}><Text style={[s.choiceText,{color:p?.secondaryTextColor??'rgba(255,255,255,.55)'},active&&{color:p?.accentColor??'#f3d675'}]}>{label}</Text></TouchableOpacity>}`,
`function MonitorChoice({active,label,onPress,onLongPress}:{active:boolean;label:string;onPress:()=>void;onLongPress?:()=>void}){const p=theme();const pressedAt=useRef(0);const longFired=useRef(false);return <TouchableOpacity delayLongPress={500} onPressIn={()=>{pressedAt.current=Date.now();longFired.current=false}} onLongPress={()=>{longFired.current=true;onLongPress?.()}} onPress={()=>{const elapsed=Date.now()-pressedAt.current;if(!longFired.current&&elapsed<300)onPress();longFired.current=false}} style={[s.choice,active&&s.choiceActive,active&&{borderColor:p?.accentColor??'#d4af37'}]}><Text style={[s.choiceText,{color:p?.secondaryTextColor??'rgba(255,255,255,.55)'},active&&{color:p?.accentColor??'#f3d675'}]}>{label}</Text></TouchableOpacity>}`,'MonitorChoice long press');
 src=replace(src,
`const mp=prefs.monitoring.floating;const patchMonitor=(x:Partial<MonitorProfile>)=>{const next={...mp,...x};if(x.width!=null||x.height!=null)setFloatingOverlayLayoutSize(next.width,next.height);onChange({monitoring:{...prefs.monitoring,floating:next}})};`,
`const mp=prefs.monitoring.floating;const patchMonitor=(x:Partial<MonitorProfile>)=>{const normalLayout=(x.width!=null||x.height!=null)?{...mp.normalLayout,width:x.width??mp.normalLayout.width,height:x.height??mp.normalLayout.height}:(x.normalLayout?{...mp.normalLayout,...x.normalLayout}:mp.normalLayout);const miniLayout=x.miniLayout?{...mp.miniLayout,...x.miniLayout}:mp.miniLayout;const miniConfig=x.miniConfig?{...mp.miniConfig,...x.miniConfig}:mp.miniConfig;const next={...mp,...x,normalLayout,miniLayout,miniConfig,width:normalLayout.width,height:normalLayout.height};if(!next.isMinimized&&(x.width!=null||x.height!=null))setFloatingOverlayLayoutSize(normalLayout.width,normalLayout.height);onChange({monitoring:{...prefs.monitoring,floating:next}})};`,'patchMonitor dual layout');
 src=replace(src,
`{MONITOR_TEMPLATES.map(t=><MonitorChoice key={t.id} active={mp.displayMode===t.id} label={t.name} onPress={()=>{patchMonitor({displayMode:t.id,fields:templateDefaultFields(t.id),fieldsCustomized:false});setMonitorTemplateEdit(t.id)}}/>)}`,
`{MONITOR_TEMPLATES.map(t=><MonitorChoice key={t.id} active={mp.displayMode===t.id} label={t.name} onPress={()=>patchMonitor({displayMode:t.id,activeTemplateId:t.id,fields:templateDefaultFields(t.id),fieldsCustomized:false})} onLongPress={()=>setMonitorTemplateEdit(t.id)}/>)}`,'template short/long press');
 const marker=`  <Card><SectionTitle title="監控 ETF 與顯示順序" right={\`最多 \${mp.maxSymbols} 檔\`}/>`;
 const mini=`  <Card><SectionTitle title="Mini 縮小模式" right={\`\${mp.miniLayout.width} × \${mp.miniLayout.height}px\`}/><Text style={s.note}>Mini 使用獨立 Layout 與欄位設定；拖曳 / Resize 只寫入 miniLayout，雙擊 Mini 空白區恢復 normalLayout。</Text><SettingRow label="Mini 版型"><MonitorChoice active={mp.miniConfig.layoutType==='SINGLE_ROW'} label="單列" onPress={()=>patchMonitor({miniConfig:{...mp.miniConfig,layoutType:'SINGLE_ROW'}})}/><MonitorChoice active={mp.miniConfig.layoutType==='DUAL_ROW'} label="雙列" onPress={()=>patchMonitor({miniConfig:{...mp.miniConfig,layoutType:'DUAL_ROW'}})}/><MonitorChoice active={mp.miniConfig.layoutType==='LIST'} label="列表" onPress={()=>patchMonitor({miniConfig:{...mp.miniConfig,layoutType:'LIST'}})}/><MonitorChoice active={mp.miniConfig.layoutType==='MINI_CARD'} label="迷你卡片" onPress={()=>patchMonitor({miniConfig:{...mp.miniConfig,layoutType:'MINI_CARD'}})}/><MonitorChoice active={mp.miniConfig.layoutType==='GRID'} label="拼圖" onPress={()=>patchMonitor({miniConfig:{...mp.miniConfig,layoutType:'GRID'}})}/></SettingRow><SettingRow label={\`Mini 寬度 \${mp.miniLayout.width}px\`}><Stepper value={mp.miniLayout.width} min={96} max={480} step={8} onChange={width=>patchMonitor({miniLayout:{...mp.miniLayout,width}})}/></SettingRow><SettingRow label={\`Mini 高度 \${mp.miniLayout.height}px\`}><Stepper value={mp.miniLayout.height} min={40} max={360} step={8} onChange={height=>patchMonitor({miniLayout:{...mp.miniLayout,height}})}/></SettingRow><SettingRow label={\`Mini 最多顯示 \${mp.miniConfig.maxDisplayCount} 檔\`}><Stepper value={mp.miniConfig.maxDisplayCount} min={1} max={10} step={1} onChange={maxDisplayCount=>patchMonitor({miniConfig:{...mp.miniConfig,maxDisplayCount}})}/></SettingRow><SettingRow label="Mini 顯示項目"><MonitorFieldPicker choices={monitorFields} selected={mp.miniConfig.displayFields as MonitorField[]} onToggle={key=>{const current=mp.miniConfig.displayFields as MonitorField[];patchMonitor({miniConfig:{...mp.miniConfig,displayFields:current.includes(key)?current.filter(x=>x!==key):[...current,key],fieldOrder:current.includes(key)?mp.miniConfig.fieldOrder.filter(x=>x!==key):[...mp.miniConfig.fieldOrder,key]}})}} onEdit={key=>setMonitorFieldEdit(key)}/></SettingRow><SettingRow label={\`資料 / 呼吸燈更新頻率 \${mp.refreshSeconds} 秒\`}><Stepper value={mp.refreshSeconds} min={1} max={60} step={1} onChange={refreshSeconds=>patchMonitor({refreshSeconds})}/></SettingRow><Text style={s.note}>呼吸燈與資料刷新共用同一週期，不建立第二個 timer；停止更新時進入 PAUSED。</Text></Card>\n`;
 src=replace(src,marker,mini+marker,'insert mini settings');
 return src;
});

patch('modules/floating-investment-bot/android/src/main/java/com/etfpilot/floatingbot/FloatingInvestmentBotService.kt',src=>{
 src=replace(src,`  private var destroyed = false\n`,`  private var destroyed = false\n  private var refreshInFlight = false\n  private fun layoutStore() = FloatingMonitorLayoutStore(this)\n`,'native layout store');
 src=replace(src,
`  private val refreshRunnable = object : Runnable {\n    override fun run() {\n      if (destroyed) return\n      refreshQuotesInBackground()\n      val sec = payload.optDouble("refreshSeconds", 5.0)\n      val delay = if (sec <= 0.0) 1000L else max(250L, (sec * 1000.0).toLong())\n      handler.postDelayed(this, delay)\n    }\n  }`,
`  private val refreshRunnable = object : Runnable {\n    override fun run() {\n      if (destroyed) return\n      val sec = payload.optDouble("refreshSeconds", 5.0)\n      if (sec <= 0.0) { payload.put("pulseStatus", "PAUSED"); updateOverlayText(); return }\n      payload.put("pulseStatus", "REFRESHING")\n      updateOverlayText()\n      refreshQuotesInBackground()\n      handler.postDelayed(this, max(1000L, (sec * 1000.0).toLong()))\n    }\n  }`,'pulse refresh loop');
 src=replace(src,
`    val saved = getSharedPreferences(PREF, MODE_PRIVATE)\n    val customW = payload.optDouble("width", 0.0)\n    val customH = payload.optDouble("height", 0.0)\n    val savedW = saved.getInt(PREF_W, 0)\n    val savedH = saved.getInt(PREF_H, 0)\n    val size = Pair(if (savedW > 0) savedW else if (customW > 0) customW.toInt() else preset.first, if (savedH > 0) savedH else if (customH > 0) customH.toInt() else preset.second)`,
`    val store = layoutStore()\n    store.applyPayload(payload)\n    val active = store.active()\n    val size = Pair(active.width.takeIf { it > 0 } ?: preset.first, active.height.takeIf { it > 0 } ?: preset.second)`,'active layout sizing');
 src=replace(src,
`    val prefs = getSharedPreferences(PREF, MODE_PRIVATE)\n    params = WindowManager.LayoutParams(\n      dp(size.first), if (payload.optBoolean("autoHeight", true)) WindowManager.LayoutParams.WRAP_CONTENT else dp(size.second), type,`,
`    params = WindowManager.LayoutParams(\n      dp(size.first), dp(size.second), type,`,'fixed active height');
 src=replace(src,
`      x = prefs.getInt(PREF_X, dp(18))\n      y = prefs.getInt(PREF_Y, dp(180))`,
`      x = active.x\n      y = active.y`,'active layout position');
 src=replace(src,
`      p.width = dp(size.first)\n      p.height = if (payload.optBoolean("autoHeight", true)) WindowManager.LayoutParams.WRAP_CONTENT else dp(size.second)`,
`      p.width = dp(size.first)\n      p.height = dp(size.second)\n      p.x = active.x\n      p.y = active.y`,'update active bounds');
 src=replace(src,
`            try{wm.updateViewLayout(root,p)}catch(_:Throwable){}; getSharedPreferences(PREF,MODE_PRIVATE).edit().putInt(PREF_X,p.x).putInt(PREF_Y,p.y).apply()`,
`            try{wm.updateViewLayout(root,p)}catch(_:Throwable){}; val store=layoutStore();val current=store.active();store.saveActive(current.copy(x=p.x,y=p.y))`,'save drag by mode');
 src=replace(src,
`        MotionEvent.ACTION_UP->{getSharedPreferences(PREF,MODE_PRIVATE).edit().putInt(PREF_W,(p.width/resources.displayMetrics.density).toInt()).putInt(PREF_H,(p.height/resources.displayMetrics.density).toInt()).apply();if(payload.optBoolean("haptics",true))view.performHapticFeedback(android.view.HapticFeedbackConstants.CLOCK_TICK);true}`,
`        MotionEvent.ACTION_UP->{val store=layoutStore();val current=store.active();store.saveActive(current.copy(x=p.x,y=p.y,width=(p.width/resources.displayMetrics.density).toInt(),height=(p.height/resources.displayMetrics.density).toInt()));if(payload.optBoolean("haptics",true))view.performHapticFeedback(android.view.HapticFeedbackConstants.CLOCK_TICK);true}`,'save resize by mode');
 src=replace(src,
`  private fun toggleFavoriteSize(){\n    val p=params?:return;val minW=dp(max(120,payload.optInt("minWidth",120)));val minH=dp(max(48,payload.optInt("minHeight",48)));val expanded=p.width>minW*2\n    if(expanded){p.width=minW;p.height=minH}else{p.width=min(resources.displayMetrics.widthPixels-dp(16),dp(payload.optInt("width",390)));p.height=min((resources.displayMetrics.heightPixels*.72).toInt(),dp(payload.optInt("height",240)))}\n    try{wm.updateViewLayout(root,p)}catch(_:Throwable){}\n    getSharedPreferences(PREF,MODE_PRIVATE).edit().putInt(PREF_W,(p.width/resources.displayMetrics.density).toInt()).putInt(PREF_H,(p.height/resources.displayMetrics.density).toInt()).apply()\n  }`,
`  private fun toggleFavoriteSize(){\n    val p=params?:return\n    val store=layoutStore()\n    val next=if(store.isMinimized()){store.restoreNormal()}else{\n      store.saveNormal(store.normal().copy(x=p.x,y=p.y,width=(p.width/resources.displayMetrics.density).toInt(),height=(p.height/resources.displayMetrics.density).toInt()))\n      store.minimize()\n    }\n    p.x=next.x;p.y=next.y;p.width=dp(next.width);p.height=dp(next.height)\n    payload.put("isMinimized",store.isMinimized())\n    payload.put("fields",if(store.isMinimized())payload.optJSONArray("miniFields")?:payload.optJSONArray("fields") else payload.optJSONArray("normalFields")?:payload.optJSONArray("fields"))\n    try{wm.updateViewLayout(root,p)}catch(_:Throwable){}\n    updateOverlayText()\n  }`,'dual state toggle');
 src=replace(src,
`    root?.background = bg\n    if (payload.optString("mode", "bubble") == "table")`,
`    root?.background = bg\n    if (layoutStore().isMinimized()) { renderMiniOverlay(); return }\n    if (payload.optString("mode", "bubble") == "table")`,'mini renderer dispatch');
 const miniRenderer=`\n  private fun renderMiniOverlay() {\n    val host=root?:return\n    host.removeAllViews();host.setPadding(dp(6),dp(4),dp(6),dp(4))\n    val cfg=payload.optJSONObject("miniConfig")?:JSONObject()\n    val layout=cfg.optString("layoutType","LIST")\n    val lines=selectedMetricLines().take(cfg.optInt("maxDisplayCount",3).coerceIn(1,10))\n    val textColor=parseColor(payload.optString("textColor","#FFFFFF"),Color.WHITE)\n    val accent=parseColor(payload.optString("accent","#3AC7FF"),Color.CYAN)\n    val status=payload.optString("pulseStatus","IDLE")\n    val lamp=when(status){"REFRESHING"->"●";"ERROR"->"◉";"PAUSED"->"○";else->"•"}\n    val header=TextView(this).apply{text="$lamp ${payload.optString("updatedAt","--:--:--")}";textSize=8f;setTextColor(accent);gravity=Gravity.END;setPadding(dp(2),0,dp(2),dp(2))}\n    host.addView(header,LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT))\n    val columns=when(layout){"SINGLE_ROW"->max(1,lines.size);"DUAL_ROW"->max(1,(lines.size+1)/2);"GRID"->2;else->1}\n    if(layout=="LIST"||layout=="MINI_CARD"){\n      val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL}\n      lines.forEach{line->list.addView(TextView(this).apply{text=line;textSize=cfg.optDouble("fontSize",11.0).toFloat();setTextColor(textColor);setPadding(dp(4),dp(2),dp(4),dp(2));maxLines=1},LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT))}\n      host.addView(list,LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,0,1f))\n    }else{\n      val grid=GridLayout(this).apply{columnCount=columns;rowCount=GridLayout.UNDEFINED}\n      lines.forEach{line->val cell=TextView(this).apply{text=line;textSize=cfg.optDouble("fontSize",11.0).toFloat();setTextColor(textColor);gravity=Gravity.CENTER;setPadding(dp(3),dp(2),dp(3),dp(2));maxLines=1};grid.addView(cell,GridLayout.LayoutParams().apply{width=0;height=android.view.ViewGroup.LayoutParams.WRAP_CONTENT;columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f)})}\n      host.addView(grid,LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,0,1f))\n    }\n    if(!payload.optBoolean("locked",false)){val grip=TextView(this).apply{text="↘";textSize=14f;setTextColor(accent);gravity=Gravity.END};host.addView(grip,LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(22)));installResizeTouch(grip)}\n  }\n`;
 src=replace(src,`\n  private fun renderTableOverlay() {`,miniRenderer+`\n  private fun renderTableOverlay() {`,'insert mini renderer');
 src=replace(src,
`  private fun refreshQuotesInBackground() {\n    val basePayload=payload`,
`  private fun refreshQuotesInBackground() {\n    if(refreshInFlight)return\n    refreshInFlight=true\n    val basePayload=payload`,'single flight refresh');
 src=replace(src,
`            payload.put("healthy", true)\n            getSharedPreferences(PREF,MODE_PRIVATE).edit().putString(PREF_PAYLOAD,payload.toString()).apply();updateOverlayText()`,
`            payload.put("healthy", true)\n            payload.put("pulseStatus", "SUCCESS")\n            refreshInFlight=false\n            getSharedPreferences(PREF,MODE_PRIVATE).edit().putString(PREF_PAYLOAD,payload.toString()).apply();updateOverlayText()`,'refresh success status');
 src=replace(src,
`}catch(_:Throwable){handler.post{if(payload===basePayload){basePayload.put("healthy",false);updateOverlayText()}}}`,
`}catch(_:Throwable){handler.post{refreshInFlight=false;if(payload===basePayload){basePayload.put("healthy",false);basePayload.put("pulseStatus","ERROR");updateOverlayText()}}}`,'refresh error status');
 return src;
});
